import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 14
normal.family = "MonaspiceAr Nerd Font"
bold.family = "MonaspiceAr Nerd Font"
italic.family = "MonaspiceAr Nerd Font"
bold_italic.family = "MonaspiceAr Nerd Font"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9

[window.padding]
x = 25
y = 20


